[2025-06-08T15:16:05.006+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T15:14:00+00:00 [queued]>
[2025-06-08T15:16:05.010+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T15:14:00+00:00 [queued]>
[2025-06-08T15:16:05.011+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T15:16:05.019+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 15:14:00+00:00
[2025-06-08T15:16:05.028+0000] {standard_task_runner.py:60} INFO - Started process 192 to run task
[2025-06-08T15:16:05.033+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-08T15:14:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpqurjtnw8']
[2025-06-08T15:16:05.034+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask run_kafka_consumer
[2025-06-08T15:16:05.086+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T15:14:00+00:00 [running]> on host d416ae487cab
[2025-06-08T15:16:05.153+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T15:14:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T15:14:00+00:00'
[2025-06-08T15:16:05.154+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T15:16:05.155+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T15:16:05.164+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T15:16:05.382+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,381 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:16:05.382+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,382 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:16:05.383+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,382 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:16:05.383+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,382 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:16:05.383+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,382 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:16:05.383+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,382 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:16:05.383+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,382 - kafka.client - WARNING - No node available during check_version; sleeping 0.06 secs
[2025-06-08T15:16:05.441+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,441 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:16:05.442+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,441 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:16:05.442+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,441 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:16:05.442+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,441 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:16:05.442+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,441 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:16:05.442+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,441 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:16:05.443+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,441 - kafka.client - WARNING - No node available during check_version; sleeping 0.10 secs
[2025-06-08T15:16:05.548+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,547 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:16:05.549+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,547 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:16:05.549+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,547 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:16:05.549+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,548 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:16:05.550+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,548 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:16:05.550+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,548 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:16:05.550+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,548 - kafka.client - WARNING - No node available during check_version; sleeping 0.23 secs
[2025-06-08T15:16:05.778+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,777 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:16:05.779+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,778 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:16:05.779+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,778 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:16:05.779+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,778 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:16:05.780+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,778 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:16:05.780+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,778 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:16:05.780+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:05,779 - kafka.client - WARNING - No node available during check_version; sleeping 0.36 secs
[2025-06-08T15:16:06.150+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:06,143 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:16:06.156+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:06,144 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:16:06.157+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:06,144 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:16:06.159+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:06,145 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:16:06.160+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:06,146 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:16:06.160+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:06,146 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:16:06.161+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:06,146 - kafka.client - WARNING - No node available during check_version; sleeping 0.78 secs
[2025-06-08T15:16:06.933+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:06,930 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:16:06.941+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:06,932 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:16:06.942+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:06,932 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:16:06.942+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:06,932 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:16:06.942+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:06,933 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:16:06.942+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:06,933 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:16:06.942+0000] {subprocess.py:93} INFO - 2025-06-08 15:16:06,933 - kafka.client - WARNING - No node available during check_version; sleeping 0.45 secs
[2025-06-08T15:16:07.387+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T15:16:07.475+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T15:16:07.534+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T151400, start_date=20250608T151605, end_date=20250608T151607
[2025-06-08T15:16:07.594+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T15:16:07.624+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
