[2025-05-14T04:56:19.051+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_data_ingestion.setup_s3_bucket manual__2025-05-14T04:56:16+00:00 [queued]>
[2025-05-14T04:56:19.055+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_data_ingestion.setup_s3_bucket manual__2025-05-14T04:56:16+00:00 [queued]>
[2025-05-14T04:56:19.055+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-14T04:56:19.065+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): setup_s3_bucket> on 2025-05-14 04:56:16+00:00
[2025-05-14T04:56:19.079+0000] {standard_task_runner.py:60} INFO - Started process 364 to run task
[2025-05-14T04:56:19.089+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_data_ingestion', 'setup_s3_bucket', 'manual__2025-05-14T04:56:16+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_etl_dag.py', '--cfg-path', '/tmp/tmpru4i4yjw']
[2025-05-14T04:56:19.094+0000] {standard_task_runner.py:88} INFO - Job 32: Subtask setup_s3_bucket
[2025-05-14T04:56:19.167+0000] {task_command.py:423} INFO - Running <TaskInstance: ecommerce_data_ingestion.setup_s3_bucket manual__2025-05-14T04:56:16+00:00 [running]> on host 0a774477c13b
[2025-05-14T04:56:19.208+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_data_ingestion' AIRFLOW_CTX_TASK_ID='setup_s3_bucket' AIRFLOW_CTX_EXECUTION_DATE='2025-05-14T04:56:16+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-14T04:56:16+00:00'
[2025-05-14T04:56:19.228+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-05-14T04:56:23.047+0000] {ingestion_script.py:432} INFO - Bucket rj-ecommerce-data-lake already exists
[2025-05-14T04:56:23.054+0000] {python.py:201} INFO - Done. Returned value was: S3 bucket rj-ecommerce-data-lake ready for ingestion
[2025-05-14T04:56:23.107+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=ecommerce_data_ingestion, task_id=setup_s3_bucket, execution_date=20250514T045616, start_date=20250514T045619, end_date=20250514T045623
[2025-05-14T04:56:23.173+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-14T04:56:23.235+0000] {taskinstance.py:3280} INFO - 13 downstream tasks scheduled from follow-on schedule check
