[2025-06-08T16:52:04.097+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:50:00+00:00 [queued]>
[2025-06-08T16:52:04.101+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:50:00+00:00 [queued]>
[2025-06-08T16:52:04.101+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T16:52:04.106+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 16:50:00+00:00
[2025-06-08T16:52:04.108+0000] {standard_task_runner.py:60} INFO - Started process 1244 to run task
[2025-06-08T16:52:04.110+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-08T16:50:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmp9ja8rhbt']
[2025-06-08T16:52:04.111+0000] {standard_task_runner.py:88} INFO - Job 57: Subtask run_kafka_consumer
[2025-06-08T16:52:04.134+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:50:00+00:00 [running]> on host 8ca63cef15a9
[2025-06-08T16:52:04.168+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T16:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T16:50:00+00:00'
[2025-06-08T16:52:04.168+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T16:52:04.169+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T16:52:04.173+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T16:52:04.320+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,320 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:52:04.320+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,320 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:52:04.321+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,320 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:52:04.321+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,320 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:52:04.321+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,320 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:52:04.321+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,320 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:52:04.321+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,320 - kafka.client - WARNING - No node available during check_version; sleeping 0.04 secs
[2025-06-08T16:52:04.366+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,365 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:52:04.366+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,365 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:52:04.366+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,365 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:52:04.366+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,365 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:52:04.366+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,365 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:52:04.367+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,365 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:52:04.367+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,366 - kafka.client - WARNING - No node available during check_version; sleeping 0.09 secs
[2025-06-08T16:52:04.458+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,458 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:52:04.459+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,458 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:52:04.459+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,458 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:52:04.459+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,458 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:52:04.460+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,458 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:52:04.460+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,458 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:52:04.460+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,458 - kafka.client - WARNING - No node available during check_version; sleeping 0.16 secs
[2025-06-08T16:52:04.626+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,624 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:52:04.628+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,626 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:52:04.628+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,626 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:52:04.629+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,626 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:52:04.629+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,627 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:52:04.630+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,627 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:52:04.630+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,627 - kafka.client - WARNING - No node available during check_version; sleeping 0.32 secs
[2025-06-08T16:52:04.954+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,952 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:52:04.956+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,953 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:52:04.956+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,953 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:52:04.956+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,954 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:52:04.957+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,954 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:52:04.957+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,954 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:52:04.957+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:04,954 - kafka.client - WARNING - No node available during check_version; sleeping 0.80 secs
[2025-06-08T16:52:05.762+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:05,761 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:52:05.763+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:05,762 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:52:05.764+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:05,762 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:52:05.764+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:05,762 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:52:05.765+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:05,763 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:52:05.765+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:05,763 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:52:05.765+0000] {subprocess.py:93} INFO - 2025-06-08 16:52:05,763 - kafka.client - WARNING - No node available during check_version; sleeping 0.56 secs
[2025-06-08T16:52:06.323+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T16:52:06.376+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T16:52:06.395+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T165000, start_date=20250608T165204, end_date=20250608T165206
[2025-06-08T16:52:06.417+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T16:52:06.427+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
