[2025-06-08T14:52:03.734+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:50:00+00:00 [queued]>
[2025-06-08T14:52:03.738+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:50:00+00:00 [queued]>
[2025-06-08T14:52:03.739+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T14:52:03.744+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 14:50:00+00:00
[2025-06-08T14:52:03.747+0000] {standard_task_runner.py:60} INFO - Started process 704 to run task
[2025-06-08T14:52:03.749+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-08T14:50:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpc6l4bbmr']
[2025-06-08T14:52:03.750+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask run_kafka_consumer
[2025-06-08T14:52:03.774+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:50:00+00:00 [running]> on host 0a5990b3e6c5
[2025-06-08T14:52:03.812+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T14:50:00+00:00'
[2025-06-08T14:52:03.813+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T14:52:03.813+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T14:52:03.822+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T14:52:03.975+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:03,975 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:52:03.975+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:03,975 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:52:03.976+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:03,975 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:52:03.976+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:03,975 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:52:03.976+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:03,975 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:52:03.976+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:03,975 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:52:03.976+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:03,975 - kafka.client - WARNING - No node available during check_version; sleeping 0.05 secs
[2025-06-08T14:52:04.023+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,023 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:52:04.023+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,023 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:52:04.024+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,023 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:52:04.024+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,023 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:52:04.024+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,023 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:52:04.024+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,023 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:52:04.024+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,023 - kafka.client - WARNING - No node available during check_version; sleeping 0.08 secs
[2025-06-08T14:52:04.108+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,107 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:52:04.108+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,107 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:52:04.109+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,107 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:52:04.109+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,108 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:52:04.109+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,108 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:52:04.109+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,108 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:52:04.110+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,108 - kafka.client - WARNING - No node available during check_version; sleeping 0.17 secs
[2025-06-08T14:52:04.285+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,283 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:52:04.287+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,284 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:52:04.288+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,285 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:52:04.288+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,285 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:52:04.288+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,286 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:52:04.289+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,286 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:52:04.289+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,286 - kafka.client - WARNING - No node available during check_version; sleeping 0.34 secs
[2025-06-08T14:52:04.628+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,627 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:52:04.629+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,628 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:52:04.630+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,628 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:52:04.630+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,628 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:52:04.630+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,628 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:52:04.630+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,628 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:52:04.630+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:04,628 - kafka.client - WARNING - No node available during check_version; sleeping 0.93 secs
[2025-06-08T14:52:05.561+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:05,560 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:52:05.562+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:05,561 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:52:05.562+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:05,561 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:52:05.563+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:05,561 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:52:05.563+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:05,561 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:52:05.563+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:05,561 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:52:05.564+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:05,561 - kafka.client - WARNING - No node available during check_version; sleeping 0.41 secs
[2025-06-08T14:52:05.977+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T14:52:06.034+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T14:52:06.063+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T145000, start_date=20250608T145203, end_date=20250608T145206
[2025-06-08T14:52:06.106+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T14:52:06.123+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
