[2025-06-08T15:12:04.514+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T15:10:00+00:00 [queued]>
[2025-06-08T15:12:04.519+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T15:10:00+00:00 [queued]>
[2025-06-08T15:12:04.519+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T15:12:04.525+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 15:10:00+00:00
[2025-06-08T15:12:04.529+0000] {standard_task_runner.py:60} INFO - Started process 412 to run task
[2025-06-08T15:12:04.531+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-08T15:10:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmp8ai6_5ef']
[2025-06-08T15:12:04.532+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask run_kafka_consumer
[2025-06-08T15:12:04.564+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T15:10:00+00:00 [running]> on host 84e1bb802fd3
[2025-06-08T15:12:04.613+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T15:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T15:10:00+00:00'
[2025-06-08T15:12:04.614+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T15:12:04.615+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T15:12:04.622+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T15:12:04.818+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,817 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:12:04.819+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,818 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:12:04.819+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,819 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:12:04.819+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,819 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:12:04.820+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,819 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:12:04.820+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,819 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:12:04.820+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,819 - kafka.client - WARNING - No node available during check_version; sleeping 0.05 secs
[2025-06-08T15:12:04.871+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,870 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:12:04.871+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,870 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:12:04.871+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,870 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:12:04.872+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,870 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:12:04.872+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,870 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:12:04.872+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,870 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:12:04.872+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,871 - kafka.client - WARNING - No node available during check_version; sleeping 0.10 secs
[2025-06-08T15:12:04.978+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,976 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:12:04.978+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,977 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:12:04.978+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,977 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:12:04.979+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,977 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:12:04.979+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,977 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:12:04.979+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,977 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:12:04.980+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:04,977 - kafka.client - WARNING - No node available during check_version; sleeping 0.17 secs
[2025-06-08T15:12:05.148+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:05,147 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:12:05.149+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:05,148 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:12:05.150+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:05,148 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:12:05.150+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:05,149 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:12:05.151+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:05,149 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:12:05.151+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:05,149 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:12:05.152+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:05,149 - kafka.client - WARNING - No node available during check_version; sleeping 0.40 secs
[2025-06-08T15:12:05.553+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:05,552 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:12:05.554+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:05,553 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:12:05.555+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:05,553 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:12:05.555+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:05,553 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:12:05.555+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:05,554 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:12:05.556+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:05,554 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:12:05.556+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:05,554 - kafka.client - WARNING - No node available during check_version; sleeping 0.75 secs
[2025-06-08T15:12:06.374+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:06,360 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:12:06.388+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:06,369 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:12:06.388+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:06,369 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:12:06.389+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:06,372 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:12:06.389+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:06,373 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:12:06.389+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:06,373 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:12:06.389+0000] {subprocess.py:93} INFO - 2025-06-08 15:12:06,374 - kafka.client - WARNING - No node available during check_version; sleeping 0.44 secs
[2025-06-08T15:12:06.817+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T15:12:06.893+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T15:12:06.936+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T151000, start_date=20250608T151204, end_date=20250608T151206
[2025-06-08T15:12:07.019+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T15:12:07.112+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
