[2025-06-09T15:16:32.561+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.run_ods_layer manual__2025-06-09T15:14:24.469659+00:00 [queued]>
[2025-06-09T15:16:32.566+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.run_ods_layer manual__2025-06-09T15:14:24.469659+00:00 [queued]>
[2025-06-09T15:16:32.567+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-06-09T15:16:32.574+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_ods_layer> on 2025-06-09 15:14:24.469659+00:00
[2025-06-09T15:16:32.577+0000] {standard_task_runner.py:60} INFO - Started process 648 to run task
[2025-06-09T15:16:32.580+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'run_ods_layer', 'manual__2025-06-09T15:14:24.469659+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpg1afm8gx']
[2025-06-09T15:16:32.581+0000] {standard_task_runner.py:88} INFO - Job 159: Subtask run_ods_layer
[2025-06-09T15:16:32.625+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_dag.run_ods_layer manual__2025-06-09T15:14:24.469659+00:00 [running]> on host ed7c78a1ebb0
[2025-06-09T15:16:32.675+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='run_ods_layer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T15:14:24.469659+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T15:14:24.469659+00:00'
[2025-06-09T15:16:32.676+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-09T15:16:32.677+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/ecom_etl && python ods_layer.py']
[2025-06-09T15:16:32.683+0000] {subprocess.py:86} INFO - Output:
[2025-06-09T15:16:33.264+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:33,264 - ods_snowflake_copy_script - INFO - --- Starting Optimized ODS Ingestion Script for Snowflake (COPY INTO) ---
[2025-06-09T15:16:33.394+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:33,393 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.8.18, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.34
[2025-06-09T15:16:33.395+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:33,393 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-06-09T15:16:34.934+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:34,934 - ods_snowflake_copy_script - INFO - Successfully connected to Snowflake.
[2025-06-09T15:16:34.937+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:34,934 - ods_snowflake_copy_script - INFO - Creating ECOM_ODS database if it doesn't exist...
[2025-06-09T15:16:34.937+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:34,934 - snowflake.connector.cursor - INFO - query: [CREATE DATABASE IF NOT EXISTS ECOM_ODS]
[2025-06-09T15:16:35.252+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:35,252 - snowflake.connector.cursor - INFO - query execution done
[2025-06-09T15:16:35.253+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:35,252 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1
[2025-06-09T15:16:35.253+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:35,253 - snowflake.connector.cursor - INFO - query: [USE DATABASE ECOM_ODS]
[2025-06-09T15:16:35.564+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:35,564 - snowflake.connector.cursor - INFO - query execution done
[2025-06-09T15:16:35.565+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:35,564 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1
[2025-06-09T15:16:35.566+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:35,564 - ods_snowflake_copy_script - INFO - Creating PUBLIC schema if it doesn't exist...
[2025-06-09T15:16:35.566+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:35,565 - snowflake.connector.cursor - INFO - query: [CREATE SCHEMA IF NOT EXISTS PUBLIC]
[2025-06-09T15:16:35.879+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:35,879 - snowflake.connector.cursor - INFO - query execution done
[2025-06-09T15:16:35.880+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:35,879 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1
[2025-06-09T15:16:35.880+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:35,879 - snowflake.connector.cursor - INFO - query: [USE SCHEMA PUBLIC]
[2025-06-09T15:16:36.195+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:36,194 - snowflake.connector.cursor - INFO - query execution done
[2025-06-09T15:16:36.195+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:36,195 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1
[2025-06-09T15:16:36.195+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:36,195 - ods_snowflake_copy_script - INFO - Database and schema setup completed successfully.
[2025-06-09T15:16:36.196+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:36,195 - snowflake.connector.cursor - INFO - query: [USE DATABASE ECOM_ODS]
[2025-06-09T15:16:36.507+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:36,506 - snowflake.connector.cursor - INFO - query execution done
[2025-06-09T15:16:36.507+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:36,507 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1
[2025-06-09T15:16:36.508+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:36,507 - snowflake.connector.cursor - INFO - query: [USE SCHEMA PUBLIC]
[2025-06-09T15:16:36.815+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:36,815 - snowflake.connector.cursor - INFO - query execution done
[2025-06-09T15:16:36.815+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:36,815 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1
[2025-06-09T15:16:36.816+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:36,815 - snowflake.connector.cursor - INFO - query: [CREATE OR REPLACE FILE FORMAT PARQUET_FORMAT_WITH_AUTO_TIMESTAMP TYPE = 'PARQUET...]
[2025-06-09T15:16:37.149+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:37,149 - snowflake.connector.cursor - INFO - query execution done
[2025-06-09T15:16:37.150+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:37,149 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1
[2025-06-09T15:16:37.150+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:37,149 - ods_snowflake_copy_script - INFO - Successfully created or replaced file format 'PARQUET_FORMAT_WITH_AUTO_TIMESTAMP'
[2025-06-09T15:16:37.151+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:37,149 - ods_snowflake_copy_script - INFO - Creating external stage 'S3_RAW_DATA_STAGE'...
[2025-06-09T15:16:37.152+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:37,149 - snowflake.connector.cursor - INFO - query: [DROP STAGE IF EXISTS S3_RAW_DATA_STAGE]
[2025-06-09T15:16:37.492+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:37,492 - snowflake.connector.cursor - INFO - query execution done
[2025-06-09T15:16:37.493+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:37,492 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1
[2025-06-09T15:16:37.494+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:37,493 - ods_snowflake_copy_script - ERROR - Error creating external stage: name 'AWS_SECRET_KEY' is not defined
[2025-06-09T15:16:37.494+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:37,493 - ods_snowflake_copy_script - ERROR - An error occurred in the main process: name 'AWS_SECRET_KEY' is not defined
[2025-06-09T15:16:37.495+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:37,493 - snowflake.connector.connection - INFO - closed
[2025-06-09T15:16:37.796+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:37,795 - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session
[2025-06-09T15:16:38.090+0000] {subprocess.py:93} INFO - 2025-06-09 15:16:38,089 - ods_snowflake_copy_script - INFO - Snowflake connection closed.
[2025-06-09T15:16:38.093+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-09T15:16:38.093+0000] {subprocess.py:93} INFO -   File "ods_layer.py", line 454, in <module>
[2025-06-09T15:16:38.093+0000] {subprocess.py:93} INFO -     main()
[2025-06-09T15:16:38.093+0000] {subprocess.py:93} INFO -   File "ods_layer.py", line 398, in main
[2025-06-09T15:16:38.094+0000] {subprocess.py:93} INFO -     create_external_stage(conn)
[2025-06-09T15:16:38.094+0000] {subprocess.py:93} INFO -   File "ods_layer.py", line 249, in create_external_stage
[2025-06-09T15:16:38.094+0000] {subprocess.py:93} INFO -     AWS_SECRET_KEY = '{AWS_SECRET_KEY}'
[2025-06-09T15:16:38.094+0000] {subprocess.py:93} INFO - NameError: name 'AWS_SECRET_KEY' is not defined
[2025-06-09T15:16:38.308+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-09T15:16:38.333+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-09T15:16:38.339+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_dag, task_id=run_ods_layer, execution_date=20250609T151424, start_date=20250609T151632, end_date=20250609T151638
[2025-06-09T15:16:38.354+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 159 for task run_ods_layer (Bash command failed. The command returned a non-zero exit code 1.; 648)
[2025-06-09T15:16:38.371+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-09T15:16:38.395+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
