[2025-06-08T16:50:03.954+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:48:00+00:00 [queued]>
[2025-06-08T16:50:03.958+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:48:00+00:00 [queued]>
[2025-06-08T16:50:03.958+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T16:50:03.963+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 16:48:00+00:00
[2025-06-08T16:50:03.966+0000] {standard_task_runner.py:60} INFO - Started process 1176 to run task
[2025-06-08T16:50:03.969+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-08T16:48:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmp756qu3z8']
[2025-06-08T16:50:03.970+0000] {standard_task_runner.py:88} INFO - Job 55: Subtask run_kafka_consumer
[2025-06-08T16:50:03.993+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:48:00+00:00 [running]> on host 8ca63cef15a9
[2025-06-08T16:50:04.028+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T16:48:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T16:48:00+00:00'
[2025-06-08T16:50:04.029+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T16:50:04.029+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T16:50:04.034+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T16:50:04.185+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,184 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:50:04.185+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,185 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:50:04.185+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,185 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:50:04.185+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,185 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:50:04.186+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,185 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:50:04.186+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,185 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:50:04.186+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,185 - kafka.client - WARNING - No node available during check_version; sleeping 0.05 secs
[2025-06-08T16:50:04.241+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,240 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:50:04.241+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,240 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:50:04.241+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,240 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:50:04.242+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,240 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:50:04.242+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,240 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:50:04.242+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,240 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:50:04.242+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,240 - kafka.client - WARNING - No node available during check_version; sleeping 0.11 secs
[2025-06-08T16:50:04.360+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,359 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:50:04.361+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,360 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:50:04.361+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,360 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:50:04.361+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,360 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:50:04.362+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,360 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:50:04.362+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,360 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:50:04.363+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,360 - kafka.client - WARNING - No node available during check_version; sleeping 0.19 secs
[2025-06-08T16:50:04.552+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,550 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:50:04.553+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,551 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:50:04.554+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,551 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:50:04.554+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,552 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:50:04.554+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,552 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:50:04.555+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,552 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:50:04.555+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,552 - kafka.client - WARNING - No node available during check_version; sleeping 0.32 secs
[2025-06-08T16:50:04.875+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,874 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:50:04.876+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,874 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:50:04.877+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,875 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:50:04.877+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,875 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:50:04.877+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,875 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:50:04.878+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,875 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:50:04.878+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:04,875 - kafka.client - WARNING - No node available during check_version; sleeping 0.86 secs
[2025-06-08T16:50:05.747+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:05,746 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:50:05.748+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:05,746 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:50:05.748+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:05,747 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:50:05.749+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:05,747 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:50:05.750+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:05,747 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:50:05.750+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:05,747 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:50:05.750+0000] {subprocess.py:93} INFO - 2025-06-08 16:50:05,748 - kafka.client - WARNING - No node available during check_version; sleeping 0.44 secs
[2025-06-08T16:50:06.189+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T16:50:06.245+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T16:50:06.276+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T164800, start_date=20250608T165003, end_date=20250608T165006
[2025-06-08T16:50:06.310+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T16:50:06.328+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
