[2025-06-08T14:35:19.962+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer manual__2025-06-08T14:35:13.773650+00:00 [queued]>
[2025-06-08T14:35:19.973+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer manual__2025-06-08T14:35:13.773650+00:00 [queued]>
[2025-06-08T14:35:19.974+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T14:35:19.980+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 14:35:13.773650+00:00
[2025-06-08T14:35:19.984+0000] {standard_task_runner.py:60} INFO - Started process 151 to run task
[2025-06-08T14:35:19.992+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'manual__2025-06-08T14:35:13.773650+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpp63tx42t']
[2025-06-08T14:35:19.993+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask run_kafka_consumer
[2025-06-08T14:35:20.042+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer manual__2025-06-08T14:35:13.773650+00:00 [running]> on host 0a5990b3e6c5
[2025-06-08T14:35:20.093+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:35:13.773650+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T14:35:13.773650+00:00'
[2025-06-08T14:35:20.097+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T14:35:20.100+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T14:35:20.110+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T14:35:20.421+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,421 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:35:20.423+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,421 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:35:20.423+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,422 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:35:20.424+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,422 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:35:20.427+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,422 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:35:20.427+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,422 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:35:20.427+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,422 - kafka.client - WARNING - No node available during check_version; sleeping 0.06 secs
[2025-06-08T14:35:20.484+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,484 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:35:20.485+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,484 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:35:20.485+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,484 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:35:20.486+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,484 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:35:20.486+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,485 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:35:20.486+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,485 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:35:20.486+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,485 - kafka.client - WARNING - No node available during check_version; sleeping 0.10 secs
[2025-06-08T14:35:20.583+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,583 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:35:20.584+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,583 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:35:20.584+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,583 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:35:20.584+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,583 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:35:20.584+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,584 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:35:20.584+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,584 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:35:20.584+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,584 - kafka.client - WARNING - No node available during check_version; sleeping 0.19 secs
[2025-06-08T14:35:20.774+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,774 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:35:20.775+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,774 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:35:20.777+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,774 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:35:20.777+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,775 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:35:20.778+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,775 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:35:20.779+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,775 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:35:20.779+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:20,776 - kafka.client - WARNING - No node available during check_version; sleeping 0.37 secs
[2025-06-08T14:35:21.144+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:21,144 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:35:21.146+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:21,144 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:35:21.146+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:21,145 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:35:21.146+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:21,145 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:35:21.147+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:21,146 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:35:21.147+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:21,146 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:35:21.147+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:21,146 - kafka.client - WARNING - No node available during check_version; sleeping 0.65 secs
[2025-06-08T14:35:21.798+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:21,797 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:35:21.800+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:21,798 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:35:21.800+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:21,798 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:35:21.801+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:21,799 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:35:21.801+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:21,799 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:35:21.802+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:21,799 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:35:21.802+0000] {subprocess.py:93} INFO - 2025-06-08 14:35:21,800 - kafka.client - WARNING - No node available during check_version; sleeping 0.62 secs
[2025-06-08T14:35:22.426+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T14:35:22.493+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T14:35:22.529+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T143513, start_date=20250608T143519, end_date=20250608T143522
[2025-06-08T14:35:22.600+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T14:35:22.636+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
