[2025-06-08T16:32:04.630+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:30:00+00:00 [queued]>
[2025-06-08T16:32:04.634+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:30:00+00:00 [queued]>
[2025-06-08T16:32:04.634+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T16:32:04.639+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 16:30:00+00:00
[2025-06-08T16:32:04.641+0000] {standard_task_runner.py:60} INFO - Started process 596 to run task
[2025-06-08T16:32:04.643+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-08T16:30:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmp0h5ah8v9']
[2025-06-08T16:32:04.644+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask run_kafka_consumer
[2025-06-08T16:32:04.665+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:30:00+00:00 [running]> on host 8ca63cef15a9
[2025-06-08T16:32:04.707+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T16:30:00+00:00'
[2025-06-08T16:32:04.707+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T16:32:04.708+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T16:32:04.712+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T16:32:04.854+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:04,853 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:32:04.854+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:04,854 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:32:04.854+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:04,854 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:32:04.854+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:04,854 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:32:04.854+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:04,854 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:32:04.854+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:04,854 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:32:04.855+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:04,854 - kafka.client - WARNING - No node available during check_version; sleeping 0.05 secs
[2025-06-08T16:32:04.917+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:04,917 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:32:04.918+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:04,917 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:32:04.918+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:04,917 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:32:04.918+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:04,917 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:32:04.918+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:04,917 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:32:04.919+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:04,917 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:32:04.919+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:04,917 - kafka.client - WARNING - No node available during check_version; sleeping 0.08 secs
[2025-06-08T16:32:05.004+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,003 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:32:05.005+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,003 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:32:05.007+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,003 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:32:05.007+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,004 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:32:05.007+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,004 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:32:05.008+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,004 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:32:05.008+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,004 - kafka.client - WARNING - No node available during check_version; sleeping 0.20 secs
[2025-06-08T16:32:05.210+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,209 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:32:05.211+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,209 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:32:05.211+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,209 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:32:05.212+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,210 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:32:05.212+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,210 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:32:05.213+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,210 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:32:05.213+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,210 - kafka.client - WARNING - No node available during check_version; sleeping 0.34 secs
[2025-06-08T16:32:05.550+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,549 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:32:05.552+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,550 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:32:05.553+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,550 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:32:05.554+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,551 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:32:05.554+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,551 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:32:05.555+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,551 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:32:05.555+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:05,552 - kafka.client - WARNING - No node available during check_version; sleeping 0.68 secs
[2025-06-08T16:32:06.241+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:06,238 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:32:06.242+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:06,239 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:32:06.243+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:06,240 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:32:06.244+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:06,240 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:32:06.244+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:06,241 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:32:06.245+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:06,241 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:32:06.246+0000] {subprocess.py:93} INFO - 2025-06-08 16:32:06,242 - kafka.client - WARNING - No node available during check_version; sleeping 0.61 secs
[2025-06-08T16:32:06.853+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T16:32:06.892+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T16:32:06.908+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T163000, start_date=20250608T163204, end_date=20250608T163206
[2025-06-08T16:32:06.947+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T16:32:06.959+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
