[2025-06-08T14:42:03.978+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:40:00+00:00 [queued]>
[2025-06-08T14:42:03.982+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:40:00+00:00 [queued]>
[2025-06-08T14:42:03.982+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T14:42:03.988+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 14:40:00+00:00
[2025-06-08T14:42:03.990+0000] {standard_task_runner.py:60} INFO - Started process 379 to run task
[2025-06-08T14:42:03.994+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-08T14:40:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpu3biw5k2']
[2025-06-08T14:42:03.996+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask run_kafka_consumer
[2025-06-08T14:42:04.024+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:40:00+00:00 [running]> on host 0a5990b3e6c5
[2025-06-08T14:42:04.067+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T14:40:00+00:00'
[2025-06-08T14:42:04.068+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T14:42:04.069+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T14:42:04.074+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T14:42:04.233+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,233 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:42:04.234+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,233 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:42:04.234+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,233 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:42:04.234+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,233 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:42:04.235+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,233 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:42:04.235+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,233 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:42:04.235+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,234 - kafka.client - WARNING - No node available during check_version; sleeping 0.05 secs
[2025-06-08T14:42:04.285+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,285 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:42:04.286+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,285 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:42:04.286+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,285 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:42:04.286+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,285 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:42:04.286+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,285 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:42:04.286+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,285 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:42:04.287+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,285 - kafka.client - WARNING - No node available during check_version; sleeping 0.09 secs
[2025-06-08T14:42:04.373+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,372 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:42:04.373+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,372 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:42:04.373+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,372 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:42:04.374+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,372 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:42:04.374+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,372 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:42:04.374+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,372 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:42:04.374+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,372 - kafka.client - WARNING - No node available during check_version; sleeping 0.20 secs
[2025-06-08T14:42:04.577+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,575 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:42:04.578+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,576 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:42:04.579+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,576 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:42:04.580+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,577 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:42:04.580+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,577 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:42:04.581+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,577 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:42:04.581+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:04,578 - kafka.client - WARNING - No node available during check_version; sleeping 0.47 secs
[2025-06-08T14:42:05.061+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:05,057 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:42:05.062+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:05,058 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:42:05.062+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:05,058 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:42:05.063+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:05,058 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:42:05.064+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:05,059 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:42:05.064+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:05,061 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:42:05.065+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:05,062 - kafka.client - WARNING - No node available during check_version; sleeping 0.91 secs
[2025-06-08T14:42:05.977+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:05,977 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:42:05.978+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:05,977 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:42:05.978+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:05,978 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:42:05.979+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:05,978 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:42:05.979+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:05,978 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:42:05.979+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:05,978 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:42:05.979+0000] {subprocess.py:93} INFO - 2025-06-08 14:42:05,978 - kafka.client - WARNING - No node available during check_version; sleeping 0.25 secs
[2025-06-08T14:42:06.237+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T14:42:06.284+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T14:42:06.308+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T144000, start_date=20250608T144203, end_date=20250608T144206
[2025-06-08T14:42:06.323+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T14:42:06.339+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
