[2025-06-08T14:44:03.906+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:42:00+00:00 [queued]>
[2025-06-08T14:44:03.911+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:42:00+00:00 [queued]>
[2025-06-08T14:44:03.911+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T14:44:03.917+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 14:42:00+00:00
[2025-06-08T14:44:03.920+0000] {standard_task_runner.py:60} INFO - Started process 447 to run task
[2025-06-08T14:44:03.923+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-08T14:42:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpiuvcar4o']
[2025-06-08T14:44:03.923+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask run_kafka_consumer
[2025-06-08T14:44:03.958+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:42:00+00:00 [running]> on host 0a5990b3e6c5
[2025-06-08T14:44:03.997+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:42:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T14:42:00+00:00'
[2025-06-08T14:44:03.998+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T14:44:03.999+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T14:44:04.005+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T14:44:04.165+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,165 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:44:04.165+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,165 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:44:04.166+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,165 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:44:04.166+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,165 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:44:04.166+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,165 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:44:04.166+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,165 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:44:04.166+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,165 - kafka.client - WARNING - No node available during check_version; sleeping 0.06 secs
[2025-06-08T14:44:04.223+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,222 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:44:04.224+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,222 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:44:04.224+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,223 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:44:04.224+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,223 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:44:04.224+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,223 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:44:04.224+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,223 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:44:04.225+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,223 - kafka.client - WARNING - No node available during check_version; sleeping 0.10 secs
[2025-06-08T14:44:04.328+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,328 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:44:04.329+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,328 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:44:04.329+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,328 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:44:04.330+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,328 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:44:04.330+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,329 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:44:04.330+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,329 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:44:04.331+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,329 - kafka.client - WARNING - No node available during check_version; sleeping 0.20 secs
[2025-06-08T14:44:04.535+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,532 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:44:04.536+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,533 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:44:04.537+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,533 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:44:04.537+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,534 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:44:04.537+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,534 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:44:04.538+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,534 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:44:04.538+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,534 - kafka.client - WARNING - No node available during check_version; sleeping 0.39 secs
[2025-06-08T14:44:04.931+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,931 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:44:04.932+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,931 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:44:04.933+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,931 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:44:04.933+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,932 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:44:04.934+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,932 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:44:04.934+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,932 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:44:04.934+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:04,932 - kafka.client - WARNING - No node available during check_version; sleeping 0.65 secs
[2025-06-08T14:44:05.585+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:05,584 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:44:05.587+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:05,585 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:44:05.587+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:05,585 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:44:05.588+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:05,586 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:44:05.588+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:05,586 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:44:05.589+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:05,586 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:44:05.589+0000] {subprocess.py:93} INFO - 2025-06-08 14:44:05,586 - kafka.client - WARNING - No node available during check_version; sleeping 0.58 secs
[2025-06-08T14:44:06.167+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T14:44:06.221+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T14:44:06.240+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T144200, start_date=20250608T144403, end_date=20250608T144406
[2025-06-08T14:44:06.256+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T14:44:06.266+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
