[2025-06-08T14:46:04.677+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:44:00+00:00 [queued]>
[2025-06-08T14:46:04.685+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:44:00+00:00 [queued]>
[2025-06-08T14:46:04.685+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T14:46:04.691+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 14:44:00+00:00
[2025-06-08T14:46:04.694+0000] {standard_task_runner.py:60} INFO - Started process 500 to run task
[2025-06-08T14:46:04.703+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-08T14:44:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpwosb7ibr']
[2025-06-08T14:46:04.705+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask run_kafka_consumer
[2025-06-08T14:46:04.740+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:44:00+00:00 [running]> on host 0a5990b3e6c5
[2025-06-08T14:46:04.786+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:44:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T14:44:00+00:00'
[2025-06-08T14:46:04.787+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T14:46:04.788+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T14:46:04.794+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T14:46:04.984+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:04,984 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:46:04.985+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:04,985 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:46:04.985+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:04,985 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:46:04.986+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:04,985 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:46:04.986+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:04,985 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:46:04.986+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:04,985 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:46:04.986+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:04,985 - kafka.client - WARNING - No node available during check_version; sleeping 0.05 secs
[2025-06-08T14:46:05.036+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,035 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:46:05.037+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,036 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:46:05.037+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,036 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:46:05.037+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,036 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:46:05.037+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,036 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:46:05.037+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,036 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:46:05.038+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,036 - kafka.client - WARNING - No node available during check_version; sleeping 0.09 secs
[2025-06-08T14:46:05.133+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,133 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:46:05.135+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,133 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:46:05.135+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,133 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:46:05.135+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,134 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:46:05.135+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,134 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:46:05.136+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,134 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:46:05.136+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,134 - kafka.client - WARNING - No node available during check_version; sleeping 0.21 secs
[2025-06-08T14:46:05.352+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,349 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:46:05.354+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,350 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:46:05.355+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,350 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:46:05.355+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,350 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:46:05.356+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,351 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:46:05.356+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,351 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:46:05.356+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,351 - kafka.client - WARNING - No node available during check_version; sleeping 0.35 secs
[2025-06-08T14:46:05.705+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,704 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:46:05.706+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,705 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:46:05.707+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,705 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:46:05.707+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,705 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:46:05.708+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,706 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:46:05.708+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,706 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:46:05.708+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:05,706 - kafka.client - WARNING - No node available during check_version; sleeping 0.65 secs
[2025-06-08T14:46:06.360+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:06,358 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:46:06.361+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:06,360 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:46:06.362+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:06,360 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:46:06.362+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:06,360 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:46:06.363+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:06,361 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:46:06.363+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:06,361 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:46:06.363+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:06,361 - kafka.client - WARNING - No node available during check_version; sleeping 0.62 secs
[2025-06-08T14:46:06.984+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T14:46:07.042+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T14:46:07.060+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T144400, start_date=20250608T144604, end_date=20250608T144607
[2025-06-08T14:46:07.111+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T14:46:07.123+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
