[2025-06-09T04:48:20.678+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-09T04:46:00+00:00 [queued]>
[2025-06-09T04:48:20.742+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-09T04:46:00+00:00 [queued]>
[2025-06-09T04:48:20.748+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-09T04:48:20.819+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-09 04:46:00+00:00
[2025-06-09T04:48:20.833+0000] {standard_task_runner.py:60} INFO - Started process 143 to run task
[2025-06-09T04:48:20.854+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-09T04:46:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmphmwgan1p']
[2025-06-09T04:48:20.856+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask run_kafka_consumer
[2025-06-09T04:48:20.981+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-09T04:46:00+00:00 [running]> on host 57db9ed7713c
[2025-06-09T04:48:21.259+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T04:46:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-09T04:46:00+00:00'
[2025-06-09T04:48:21.264+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-09T04:48:21.269+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-09T04:48:21.308+0000] {subprocess.py:86} INFO - Output:
[2025-06-09T04:48:21.837+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:21,836 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:48:21.843+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:21,837 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:48:21.845+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:21,837 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:48:21.848+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:21,837 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:48:21.849+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:21,838 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:48:21.852+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:21,838 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:48:21.852+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:21,838 - kafka.client - WARNING - No node available during check_version; sleeping 0.06 secs
[2025-06-09T04:48:21.896+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:21,896 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:48:21.902+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:21,896 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:48:21.904+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:21,896 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:48:21.905+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:21,896 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:48:21.906+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:21,896 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:48:21.908+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:21,896 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:48:21.909+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:21,896 - kafka.client - WARNING - No node available during check_version; sleeping 0.11 secs
[2025-06-09T04:48:22.005+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,005 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:48:22.008+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,005 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:48:22.009+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,006 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:48:22.009+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,006 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:48:22.009+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,006 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:48:22.009+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,007 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:48:22.010+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,007 - kafka.client - WARNING - No node available during check_version; sleeping 0.19 secs
[2025-06-09T04:48:22.199+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,199 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:48:22.200+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,199 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:48:22.201+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,199 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:48:22.201+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,199 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:48:22.201+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,199 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:48:22.201+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,199 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:48:22.201+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,200 - kafka.client - WARNING - No node available during check_version; sleeping 0.42 secs
[2025-06-09T04:48:22.623+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,623 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:48:22.623+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,623 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:48:22.623+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,623 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:48:22.623+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,623 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:48:22.623+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,623 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:48:22.624+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,623 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:48:22.624+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:22,623 - kafka.client - WARNING - No node available during check_version; sleeping 0.77 secs
[2025-06-09T04:48:23.401+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:23,397 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:48:23.406+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:23,398 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:48:23.406+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:23,398 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:48:23.407+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:23,400 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:48:23.407+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:23,401 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:48:23.407+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:23,401 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:48:23.407+0000] {subprocess.py:93} INFO - 2025-06-09 04:48:23,401 - kafka.client - WARNING - No node available during check_version; sleeping 0.42 secs
[2025-06-09T04:48:23.826+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-09T04:48:23.905+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-09T04:48:23.965+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250609T044600, start_date=20250609T044820, end_date=20250609T044823
[2025-06-09T04:48:24.033+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-09T04:48:24.091+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
