[2025-06-08T16:04:03.843+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:02:00+00:00 [queued]>
[2025-06-08T16:04:03.851+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:02:00+00:00 [queued]>
[2025-06-08T16:04:03.851+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T16:04:03.859+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 16:02:00+00:00
[2025-06-08T16:04:03.864+0000] {standard_task_runner.py:60} INFO - Started process 690 to run task
[2025-06-08T16:04:03.868+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-08T16:02:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpxw1qnxdd']
[2025-06-08T16:04:03.870+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask run_kafka_consumer
[2025-06-08T16:04:03.907+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:02:00+00:00 [running]> on host aece8d7c74c6
[2025-06-08T16:04:03.979+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T16:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T16:02:00+00:00'
[2025-06-08T16:04:03.984+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T16:04:03.986+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T16:04:03.993+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T16:04:04.277+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,276 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:04:04.277+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,277 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:04:04.277+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,277 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:04:04.278+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,277 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:04:04.278+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,277 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:04:04.278+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,277 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:04:04.278+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,277 - kafka.client - WARNING - No node available during check_version; sleeping 0.05 secs
[2025-06-08T16:04:04.331+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,329 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:04:04.332+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,330 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:04:04.332+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,330 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:04:04.332+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,330 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:04:04.333+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,330 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:04:04.335+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,330 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:04:04.336+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,330 - kafka.client - WARNING - No node available during check_version; sleeping 0.08 secs
[2025-06-08T16:04:04.416+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,415 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:04:04.421+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,416 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:04:04.421+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,416 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:04:04.422+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,416 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:04:04.423+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,416 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:04:04.424+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,416 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:04:04.426+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,417 - kafka.client - WARNING - No node available during check_version; sleeping 0.20 secs
[2025-06-08T16:04:04.619+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,618 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:04:04.620+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,619 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:04:04.620+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,619 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:04:04.620+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,619 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:04:04.620+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,619 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:04:04.621+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,619 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:04:04.621+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:04,619 - kafka.client - WARNING - No node available during check_version; sleeping 0.39 secs
[2025-06-08T16:04:05.010+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:05,009 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:04:05.010+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:05,010 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:04:05.010+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:05,010 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:04:05.011+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:05,010 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:04:05.011+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:05,010 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:04:05.011+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:05,010 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:04:05.011+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:05,010 - kafka.client - WARNING - No node available during check_version; sleeping 0.82 secs
[2025-06-08T16:04:05.835+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:05,834 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:04:05.836+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:05,835 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:04:05.836+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:05,835 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:04:05.837+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:05,836 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:04:05.837+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:05,836 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:04:05.837+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:05,836 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:04:05.838+0000] {subprocess.py:93} INFO - 2025-06-08 16:04:05,836 - kafka.client - WARNING - No node available during check_version; sleeping 0.44 secs
[2025-06-08T16:04:06.278+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T16:04:06.325+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T16:04:06.365+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T160200, start_date=20250608T160403, end_date=20250608T160406
[2025-06-08T16:04:06.409+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T16:04:06.435+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
