[2025-06-09T04:35:47.235+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-09T04:32:00+00:00 [queued]>
[2025-06-09T04:35:47.241+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-09T04:32:00+00:00 [queued]>
[2025-06-09T04:35:47.242+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-09T04:35:47.250+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-09 04:32:00+00:00
[2025-06-09T04:35:47.255+0000] {standard_task_runner.py:60} INFO - Started process 126 to run task
[2025-06-09T04:35:47.257+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-09T04:32:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpjxca0r8b']
[2025-06-09T04:35:47.258+0000] {standard_task_runner.py:88} INFO - Job 68: Subtask run_kafka_consumer
[2025-06-09T04:35:47.294+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-09T04:32:00+00:00 [running]> on host 00dbf994ec97
[2025-06-09T04:35:47.336+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T04:32:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-09T04:32:00+00:00'
[2025-06-09T04:35:47.337+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-09T04:35:47.338+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-09T04:35:47.344+0000] {subprocess.py:86} INFO - Output:
[2025-06-09T04:35:47.555+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,555 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:35:47.556+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,555 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:35:47.557+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,555 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:35:47.557+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,556 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:35:47.557+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,556 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:35:47.557+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,556 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:35:47.558+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,556 - kafka.client - WARNING - No node available during check_version; sleeping 0.05 secs
[2025-06-09T04:35:47.604+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,603 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:35:47.604+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,604 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:35:47.604+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,604 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:35:47.604+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,604 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:35:47.605+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,604 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:35:47.605+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,604 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:35:47.605+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,604 - kafka.client - WARNING - No node available during check_version; sleeping 0.09 secs
[2025-06-09T04:35:47.690+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,690 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:35:47.691+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,690 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:35:47.691+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,690 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:35:47.692+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,691 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:35:47.692+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,691 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:35:47.692+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,691 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:35:47.692+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,691 - kafka.client - WARNING - No node available during check_version; sleeping 0.23 secs
[2025-06-09T04:35:47.919+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,919 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:35:47.919+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,919 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:35:47.920+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,919 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:35:47.920+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,919 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:35:47.920+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,919 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:35:47.920+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,919 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:35:47.920+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:47,919 - kafka.client - WARNING - No node available during check_version; sleeping 0.47 secs
[2025-06-09T04:35:48.386+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:48,386 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:35:48.386+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:48,386 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:35:48.386+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:48,386 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:35:48.386+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:48,386 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:35:48.386+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:48,386 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:35:48.387+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:48,386 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:35:48.387+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:48,386 - kafka.client - WARNING - No node available during check_version; sleeping 0.94 secs
[2025-06-09T04:35:49.330+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:49,328 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:35:49.333+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:49,331 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:35:49.334+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:49,332 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:35:49.334+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:49,333 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:35:49.335+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:49,333 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:35:49.335+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:49,333 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:35:49.335+0000] {subprocess.py:93} INFO - 2025-06-09 04:35:49,333 - kafka.client - WARNING - No node available during check_version; sleeping 0.22 secs
[2025-06-09T04:35:49.558+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-09T04:35:49.615+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-09T04:35:49.653+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250609T043200, start_date=20250609T043547, end_date=20250609T043549
[2025-06-09T04:35:49.681+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-09T04:35:49.698+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
