[2025-06-09T04:50:05.681+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-09T04:48:00+00:00 [queued]>
[2025-06-09T04:50:05.690+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-09T04:48:00+00:00 [queued]>
[2025-06-09T04:50:05.691+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-09T04:50:05.701+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-09 04:48:00+00:00
[2025-06-09T04:50:05.709+0000] {standard_task_runner.py:60} INFO - Started process 215 to run task
[2025-06-09T04:50:05.713+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-09T04:48:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpn9uwqqd5']
[2025-06-09T04:50:05.714+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask run_kafka_consumer
[2025-06-09T04:50:05.770+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-09T04:48:00+00:00 [running]> on host 57db9ed7713c
[2025-06-09T04:50:05.913+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T04:48:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-09T04:48:00+00:00'
[2025-06-09T04:50:05.915+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-09T04:50:05.916+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-09T04:50:05.923+0000] {subprocess.py:86} INFO - Output:
[2025-06-09T04:50:06.142+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,142 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:50:06.143+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,142 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:50:06.143+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,142 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:50:06.143+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,143 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:50:06.143+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,143 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:50:06.144+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,143 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:50:06.144+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,143 - kafka.client - WARNING - No node available during check_version; sleeping 0.06 secs
[2025-06-09T04:50:06.204+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,203 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:50:06.204+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,203 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:50:06.204+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,203 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:50:06.204+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,203 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:50:06.205+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,203 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:50:06.205+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,203 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:50:06.205+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,203 - kafka.client - WARNING - No node available during check_version; sleeping 0.08 secs
[2025-06-09T04:50:06.287+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,287 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:50:06.288+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,287 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:50:06.288+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,287 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:50:06.288+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,287 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:50:06.289+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,287 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:50:06.289+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,287 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:50:06.289+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,287 - kafka.client - WARNING - No node available during check_version; sleeping 0.20 secs
[2025-06-09T04:50:06.493+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,492 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:50:06.494+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,493 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:50:06.495+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,493 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:50:06.495+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,493 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:50:06.495+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,493 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:50:06.496+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,493 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:50:06.496+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,494 - kafka.client - WARNING - No node available during check_version; sleeping 0.33 secs
[2025-06-09T04:50:06.826+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,826 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:50:06.827+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,826 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:50:06.828+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,826 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:50:06.828+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,827 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:50:06.828+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,827 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:50:06.829+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,827 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:50:06.829+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:06,827 - kafka.client - WARNING - No node available during check_version; sleeping 0.77 secs
[2025-06-09T04:50:07.604+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:07,603 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-09T04:50:07.606+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:07,606 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:50:07.607+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:07,606 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:50:07.607+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:07,607 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-09T04:50:07.608+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:07,607 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-09T04:50:07.608+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:07,607 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-09T04:50:07.608+0000] {subprocess.py:93} INFO - 2025-06-09 04:50:07,607 - kafka.client - WARNING - No node available during check_version; sleeping 0.53 secs
[2025-06-09T04:50:08.147+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-09T04:50:08.208+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-09T04:50:08.261+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250609T044800, start_date=20250609T045005, end_date=20250609T045008
[2025-06-09T04:50:08.319+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-09T04:50:08.359+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
