[2025-06-08T14:48:04.988+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:46:00+00:00 [queued]>
[2025-06-08T14:48:04.992+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:46:00+00:00 [queued]>
[2025-06-08T14:48:04.992+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T14:48:04.998+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 14:46:00+00:00
[2025-06-08T14:48:05.001+0000] {standard_task_runner.py:60} INFO - Started process 568 to run task
[2025-06-08T14:48:05.009+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-08T14:46:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpu5b_hku5']
[2025-06-08T14:48:05.011+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask run_kafka_consumer
[2025-06-08T14:48:05.045+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T14:46:00+00:00 [running]> on host 0a5990b3e6c5
[2025-06-08T14:48:05.099+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:46:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T14:46:00+00:00'
[2025-06-08T14:48:05.100+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T14:48:05.101+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T14:48:05.108+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T14:48:05.304+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,303 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:48:05.305+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,304 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:48:05.305+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,304 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:48:05.305+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,304 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:48:05.305+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,305 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:48:05.305+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,305 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:48:05.306+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,305 - kafka.client - WARNING - No node available during check_version; sleeping 0.06 secs
[2025-06-08T14:48:05.364+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,363 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:48:05.364+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,364 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:48:05.365+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,364 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:48:05.365+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,364 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:48:05.365+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,364 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:48:05.365+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,364 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:48:05.365+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,364 - kafka.client - WARNING - No node available during check_version; sleeping 0.10 secs
[2025-06-08T14:48:05.471+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,470 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:48:05.471+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,471 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:48:05.471+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,471 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:48:05.472+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,471 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:48:05.472+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,471 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:48:05.472+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,471 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:48:05.472+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,471 - kafka.client - WARNING - No node available during check_version; sleeping 0.21 secs
[2025-06-08T14:48:05.688+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,688 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:48:05.690+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,688 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:48:05.690+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,689 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:48:05.691+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,689 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:48:05.691+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,689 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:48:05.691+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,690 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:48:05.692+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:05,690 - kafka.client - WARNING - No node available during check_version; sleeping 0.47 secs
[2025-06-08T14:48:06.167+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:06,167 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:48:06.168+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:06,167 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:48:06.169+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:06,167 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:48:06.169+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:06,168 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:48:06.170+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:06,168 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:48:06.170+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:06,168 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:48:06.171+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:06,169 - kafka.client - WARNING - No node available during check_version; sleeping 0.84 secs
[2025-06-08T14:48:07.015+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:07,015 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T14:48:07.017+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:07,016 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:48:07.018+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:07,016 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:48:07.018+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:07,016 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T14:48:07.019+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:07,017 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T14:48:07.019+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:07,017 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T14:48:07.019+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:07,017 - kafka.client - WARNING - No node available during check_version; sleeping 0.28 secs
[2025-06-08T14:48:07.303+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T14:48:07.340+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T14:48:07.355+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T144600, start_date=20250608T144804, end_date=20250608T144807
[2025-06-08T14:48:07.376+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T14:48:07.387+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
