[2025-06-08T16:56:03.873+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:54:00+00:00 [queued]>
[2025-06-08T16:56:03.879+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:54:00+00:00 [queued]>
[2025-06-08T16:56:03.879+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T16:56:03.886+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 16:54:00+00:00
[2025-06-08T16:56:03.889+0000] {standard_task_runner.py:60} INFO - Started process 1379 to run task
[2025-06-08T16:56:03.892+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-08T16:54:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpd6yuwf31']
[2025-06-08T16:56:03.892+0000] {standard_task_runner.py:88} INFO - Job 61: Subtask run_kafka_consumer
[2025-06-08T16:56:03.916+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:54:00+00:00 [running]> on host 8ca63cef15a9
[2025-06-08T16:56:03.951+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T16:54:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T16:54:00+00:00'
[2025-06-08T16:56:03.952+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T16:56:03.952+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T16:56:03.957+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T16:56:04.116+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,116 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:56:04.117+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,116 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:56:04.117+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,116 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:56:04.117+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,116 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:56:04.117+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,116 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:56:04.117+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,116 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:56:04.117+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,117 - kafka.client - WARNING - No node available during check_version; sleeping 0.06 secs
[2025-06-08T16:56:04.179+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,179 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:56:04.180+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,179 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:56:04.180+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,179 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:56:04.180+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,179 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:56:04.180+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,179 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:56:04.180+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,179 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:56:04.181+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,179 - kafka.client - WARNING - No node available during check_version; sleeping 0.11 secs
[2025-06-08T16:56:04.294+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,293 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:56:04.295+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,293 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:56:04.295+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,293 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:56:04.296+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,294 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:56:04.296+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,294 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:56:04.296+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,294 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:56:04.297+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,294 - kafka.client - WARNING - No node available during check_version; sleeping 0.24 secs
[2025-06-08T16:56:04.535+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,534 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:56:04.536+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,535 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:56:04.537+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,535 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:56:04.538+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,535 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:56:04.539+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,536 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:56:04.539+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,536 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:56:04.539+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:04,536 - kafka.client - WARNING - No node available during check_version; sleeping 0.46 secs
[2025-06-08T16:56:05.001+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:05,000 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:56:05.003+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:05,001 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:56:05.003+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:05,001 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:56:05.004+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:05,002 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:56:05.004+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:05,002 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:56:05.005+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:05,002 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:56:05.005+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:05,002 - kafka.client - WARNING - No node available during check_version; sleeping 0.83 secs
[2025-06-08T16:56:05.837+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:05,836 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:56:05.839+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:05,837 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:56:05.840+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:05,837 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:56:05.841+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:05,838 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:56:05.841+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:05,838 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:56:05.842+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:05,838 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:56:05.842+0000] {subprocess.py:93} INFO - 2025-06-08 16:56:05,839 - kafka.client - WARNING - No node available during check_version; sleeping 0.28 secs
[2025-06-08T16:56:06.121+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T16:56:06.173+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T16:56:06.196+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T165400, start_date=20250608T165603, end_date=20250608T165606
[2025-06-08T16:56:06.220+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T16:56:06.233+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
