[2025-06-08T16:24:03.111+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:22:00+00:00 [queued]>
[2025-06-08T16:24:03.115+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:22:00+00:00 [queued]>
[2025-06-08T16:24:03.115+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T16:24:03.120+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 16:22:00+00:00
[2025-06-08T16:24:03.122+0000] {standard_task_runner.py:60} INFO - Started process 339 to run task
[2025-06-08T16:24:03.125+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-08T16:22:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpef53uxw_']
[2025-06-08T16:24:03.125+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask run_kafka_consumer
[2025-06-08T16:24:03.148+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T16:22:00+00:00 [running]> on host 8ca63cef15a9
[2025-06-08T16:24:03.183+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T16:22:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T16:22:00+00:00'
[2025-06-08T16:24:03.184+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T16:24:03.184+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T16:24:03.189+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T16:24:03.339+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,339 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:24:03.340+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,339 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:24:03.340+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,340 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:24:03.340+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,340 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:24:03.340+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,340 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:24:03.341+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,340 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:24:03.341+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,340 - kafka.client - WARNING - No node available during check_version; sleeping 0.05 secs
[2025-06-08T16:24:03.395+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,395 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:24:03.396+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,395 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:24:03.396+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,395 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:24:03.396+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,395 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:24:03.396+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,396 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:24:03.396+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,396 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:24:03.397+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,396 - kafka.client - WARNING - No node available during check_version; sleeping 0.08 secs
[2025-06-08T16:24:03.479+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,479 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:24:03.480+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,479 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:24:03.480+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,479 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:24:03.481+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,480 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:24:03.481+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,480 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:24:03.481+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,480 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:24:03.482+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,480 - kafka.client - WARNING - No node available during check_version; sleeping 0.21 secs
[2025-06-08T16:24:03.695+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,694 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:24:03.697+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,695 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:24:03.697+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,696 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:24:03.698+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,696 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:24:03.698+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,696 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:24:03.698+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,697 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:24:03.699+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:03,697 - kafka.client - WARNING - No node available during check_version; sleeping 0.33 secs
[2025-06-08T16:24:04.032+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:04,031 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:24:04.035+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:04,033 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:24:04.035+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:04,033 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:24:04.036+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:04,033 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:24:04.036+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:04,034 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:24:04.037+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:04,034 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:24:04.037+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:04,034 - kafka.client - WARNING - No node available during check_version; sleeping 0.85 secs
[2025-06-08T16:24:04.889+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:04,888 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T16:24:04.892+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:04,889 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:24:04.892+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:04,889 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:24:04.893+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:04,890 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T16:24:04.893+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:04,890 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T16:24:04.893+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:04,891 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T16:24:04.893+0000] {subprocess.py:93} INFO - 2025-06-08 16:24:04,891 - kafka.client - WARNING - No node available during check_version; sleeping 0.45 secs
[2025-06-08T16:24:05.341+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T16:24:05.399+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T16:24:05.428+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T162200, start_date=20250608T162403, end_date=20250608T162405
[2025-06-08T16:24:05.445+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T16:24:05.461+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
