[2025-05-14T04:59:17.524+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: ecommerce_data_ingestion.wait_for_olist_sellers_dataset __airflow_temporary_run_2025-05-14T04:58:35.490697+00:00__ [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
